### ISSUE TITLE
Re-implement consul service check in Go

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/docker-edgex-consul#3]
This repository currently will have a simple bash script calling curl and jq to see if services are ready however, this isn't ideal as `jq` and `curl` aren't statically linked, and so there's a bit of a hack in the Dockerfile consul service check script by copying the needed dynamic libraries into `/consul/scripts/` and then setting LD_LIBRARY_PATH in order to call the binaries without actually installing anything into the other containers, such as `kong-migration`, `kong`, etc.

This may be doable for Fuji, currently unclear.

**Comment by bnevis-i** [comment]
Request someone with write privileges to add security-services label to this issue.

**Comment by bnevis-i** [comment]
MOTIVATING FACTOR FOR THIS ISSUE:

On the subject of docker-compose scripts for x64 vs aarch64:

The delta are:
  - Most containers will need to switch to ubuntu-based images for aarch64 compatibility.
  - Besides that, aarch64 will need to rely on hard-coded delays INSTEAD OF dependency checker for kong-migrations and kong UNTIL we have a golang-version of the dependency checker or a statically-linked jq.  This delta is obviously more complicated than simply switching container version.

More detail:

In Fuji:
 - The docker-compose scripts between developer-scripts and blackbox-testing do not have feature parity.
 - Docker developer-scripts run because Ian implemented depenency checking hooks in all of the critical security-related containers.
 - The blackbox-testing scripts run because of the hard-coded delays between starting the services.
 - The developer-scripts docker-compose scripts use kong(-alpine) images (MUSL-based)
 - The blackbox-testing docker-compose scripts use kong-centos (glibc-based) for x64 because that is all that works on the VM.
 - The blackbox-testing docker-compose scripts use kong-ubuntu (glibc-based) for aarch64 because that is all the works on the emulator.

In Geneva:
 - The VM/emulator issues continue to exist (only images that work for Kong are glibc-based)
 - The kong images don't have a glibc version of jq installed by default
 - Until we have a golang-version of the dependency checker or a statically-linked jq, the dependency-checking scripts on the Kong containers will choke on the non-alpine Kong.  It will choke on the non-alpine Kong regardless of whether it is developer-scripts or blackbox-testing.
